libCG6: DetectorDescriptor Class Reference
DetectorDescriptor Class Reference
Base class manages the detection and description of keypoints.
#include <libCG6.h>
Public Member Functions
DetectorDescriptor (cv::Mat imgMat, std::string detector, std::string descriptor)
Constructor.
DetectorDescriptor (cv::Mat imgMat)
Constructor.
~DetectorDescriptor ()
Destructor of DetectorDescriptor Class.
int computeKeypoints (float m_thresh=17.0)
computeKeypoints : Detection of the keypoints
int describeKeypoints ()
Description of the keypoints.
void drawKeypoints ()
Display of the keypoints.
void drawSelectedKeypoints ()
Display of the keypoints.
int distributeKeypoints (int min_thresh, int keypts_desired, int nb_x, int nb_y)
distributeKeypoints : Detection and distribution of the keypoints
void getPrivateAttributes (cv::Mat &imgMat, std::string &detectorName, std::string &descriptorName)
Accessor of the private attributes.
Data Fields
featureSet featuresList
cv::Mat imageMat
Private Types
Private Member Functions
void Initialize ()
Mapping of the strings and detector/descriptor type.
void harrisDetect (cv::Mat imgSrc, std::vector< cv::KeyPoint > &keypts)
Detection of the keypoints for the Harris detector.
Private Attributes
std::string detectorType
std::string descriptorType
std::map< std::string, detectordescriptor > mapStrings
Detailed Description
Base class manages the detection and description of keypoints.
This class allows the extraction of a set of features in an image, the computation of descriptors and display of keypoints. The implemented dectectors find interesting pixels from an image to allow an efficient matching with other images. Detectors and descriptors are implemented with default values. The detectors AGAST, FAST and HARRIS do not include descriptors. Therefore they should be associated with other descriptors. The descriptors KAZE and AKAZE should be used only associated with themselves as detectors.
Definition at line 232 of file libCG6.h.
Constructor & Destructor Documentation
DetectorDescriptor::DetectorDescriptor (cv::Mat imgMat, std::string detector, std::string descriptor)
Constructor.
Constructor of the class DetectorDescriptor
Parameters
[in] imgMat : Image
[in] detector : Type of detector to use
[in] descriptor : type of descriptor to use
Returns
Nothing.
Definition at line 45 of file detectordescriptor.cpp.
Referenced by ~DetectorDescriptor().
DetectorDescriptor::DetectorDescriptor (cv::Mat imgMat)
Constructor.
Constructor of the class DetectorDescriptor with default BRISK values
Parameters
[in] imgMat : Image
Returns
Nothing.
Definition at line 65 of file detectordescriptor.cpp.
DetectorDescriptor::~DetectorDescriptor ()
Destructor of DetectorDescriptor Class.
Returns
Nothing.
Definition at line 83 of file detectordescriptor.cpp.
References descriptorType, DetectorDescriptor(), detectorType, featuresList, and imageMat.
Member Function Documentation
int DetectorDescriptor::computeKeypoints (float m_thresh = 17.0)
computeKeypoints : Detection of the keypoints
Computes the keypoints of the image stored with the detector specified in the constructor. The resulting keypoints are stored in the keypoints list of the attribute featuresList. m_thresh should be between 2 and 30 (according to BRISK value)
Returns
-1 if the type of detector does not exist 0 otherwise.
Definition at line 103 of file detectordescriptor.cpp.
int DetectorDescriptor::describeKeypoints ()
Description of the keypoints.
Computes the descriptors of the keypoints stored with the descriptor specified in the constructor. The resulting descriptors are stored in the descriptors list of the attribute featuresList or in featureSelectedList if distributeKeypoints was executed before
Returns
-1 if the type of descriptor does not exist 0 otherwise.
Definition at line 378 of file detectordescriptor.cpp.
int DetectorDescriptor::distributeKeypoints (int min_thresh, int keypts_desired, int nb_x, int nb_y)
distributeKeypoints : Detection and distribution of the keypoints
Computes the keypoints of the image stored with the detector specified in the constructor. The resulting keypoints are stored in the keypoints list of a featuresList. All keypoints are distributed equally in boxes for an homogeneous repartition of keypoints and a better homography computation m_thresh should be between 2 and 30 (according to BRISK value)
Parameters
[in] min_thresh : if a kpts response is higher the kpts is selected until the box has as many kpts as required. If there is no such kpts enough, the program fill the image zone with kpts with response below
[in] keypts_desired : number of keypoints desired in the whole image
[in] nb_x : number of boxes horizontally
[in] nb_y : number of boxes vertically
Returns
-1 if the type of detector does not exist 0 otherwise.
Fill the keypointSelectedList with keypoints of all list, one after each other
For each box
Definition at line 225 of file detectordescriptor.cpp.
void DetectorDescriptor::drawKeypoints ()
Display of the keypoints.
Draws the keypoints of the class on the image stored.
Returns
Nothing.
Definition at line 467 of file detectordescriptor.cpp.
void DetectorDescriptor::drawSelectedKeypoints ()
Display of the keypoints.
Draws the keypoints of the class on the image stored for the distributed keypoints.
Returns
Nothing.
Definition at line 484 of file detectordescriptor.cpp.
void DetectorDescriptor::getPrivateAttributes (cv::Mat & imgMat, std::string & detectorName, std::string & descriptorName)
Accessor of the private attributes.
Gets the privates attributes of a DetectorDescriptor
Parameters
[out] imgMat : the image in matrix format
[out] detectorName : Type of detector
[out] descriptorName : Type of descriptor
Returns
Nothing.
Definition at line 504 of file detectordescriptor.cpp.
Referenced by FeaturesMatching::displayMatches().
void DetectorDescriptor::harrisDetect (cv::Mat imgSrc, std::vector< cv::KeyPoint > & keypts) private
Detection of the keypoints for the Harris detector.
Computes the keypoints of the image stored for the Harris detector. The resulting keypoints are stored in the keypoints list of the attribute featuresList
Parameters
[in] imgSrc : the source image
[out] keypts : List of computed keypoints
Returns
Nothing.
Definition at line 549 of file detectordescriptor.cpp.
void DetectorDescriptor::Initialize () private
Mapping of the strings and detector/descriptor type.
Associates strings to the detector/descriptor types accepted in the enumeration list
Returns
Nothing.
Definition at line 522 of file detectordescriptor.cpp.
Field Documentation
std::string DetectorDescriptor::descriptorType private
Type of descriptor to use
Definition at line 257 of file libCG6.h.
Referenced by ~DetectorDescriptor().
std::string DetectorDescriptor::detectorType private
Type of detector to use
Definition at line 256 of file libCG6.h.
Referenced by ~DetectorDescriptor().
featureSet DetectorDescriptor::featuresList
List of keypoints coordinates and list of descriptors for the image with the image
Definition at line 247 of file libCG6.h.
Referenced by FeaturesMatching::displayMatches(), and ~DetectorDescriptor().
cv::Mat DetectorDescriptor::imageMat
Image
Definition at line 252 of file libCG6.h.
Referenced by ~DetectorDescriptor().
std::map<std::string, detectordescriptor> DetectorDescriptor::mapStrings private
Map which associates each detector/descriptor type to the corresponding string
Definition at line 258 of file libCG6.h.
The documentation for this class was generated from the following files:
libCG6.h
detectordescriptor.cpp